sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js

install:
  - npm install

before_script:
  - npm run build
  - npm run test-server &

script:
  - npm test